# Overview of the API
openapi: 3.1.1
info:
  title: Gameplay API
  version: 1.0.0
  description: API for managing running games
      
paths:
  # -------------------------
  # INTERNAL ROUTES
  # -------------------------
  /games:
    post:
      summary: Adds a new game.
      description: Create a new game instance on db and starts a GameEnging running that game logic.
      tags:
        - Games
      security:
        - ServiceIdAuth: []
          ServiceSecretAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameRequest'
      responses:
        201:
          description: Game added correctly
        500:
          description: Internal Server Error

  # -------------------------
  # PROTECTED ROUTES
  # -------------------------
  /games/{id}:
    get:
      summary: Retrieve details of a specific game
      tags:
        - Games
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the game
          schema:
            type: string
      responses:
        200:
          description: Game details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        403:
          description: You aren't in this game
        404:
          description: Game not found

components:
  # -------------------------
  # SECURITY SCHEMES
  # -------------------------
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ServiceIdAuth:
      type: apiKey
      in: header
      name: x-internal-service-id
    ServiceSecretAuth:
      type: apiKey
      in: header
      name: x-internal-secret

  # -------------------------
  # DATA SCHEMAS
  # -------------------------
  schemas:
    Player:
      type: object
      properties:
        userId:
          type: string
          example: "6585f9e2b1c2d3e4f5a6b7c0"
        name:
          type: string
          example: "MarioRossi"
        imageUrl:
          type: string
          example: "http://example.com/avatar.jpg"
        role:
          type: string
          enum: [VILLAGER, WEREWOLF, SEER, DOCTOR]
          example: "VILLAGER"
        status:
          type: string
          enum: [PLAYING, WATCHING, LEFT]
          example: PLAYING
        result:
          type: string
          enum: [PLAYING, WON, LOST]
          example: PLAYING
        votes:
          type: integer
          example: 0

    Game:
      type: object
      properties:
        id:
          type: string
          example: "6585f9e2b1c2d3e4f5a6b7c8"
        serverUrl:
          type: string
          example: "http://localhost:3000"
        numbOfPlayers:
          type: integer
          example: 8
        gameMode:
          type: string
          enum: [classic, advanced]
          example: "classic"
        roomCapacity:
          type: integer
          example: 4
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
        phase:
          type: string
          enum: [STARTUP, DAY, NIGHT, DEFENCE, GAMEOVER]
          example: "STARTUP"
        accused:
          type: string
          example: "6585f9e2b1c2d3e4f5a6b7ks"

    PlayerRequest:
      type: object
      properties:
        userId:
          type: string
          example: "6585f9e2b1c2d3e4f5a6b7c0"
        name:
          type: string
          example: "MarioRossi"
        imageUrl:
          type: string
          example: "http://example.com/avatar.jpg"

    GameRequest:
      type: object
      properties:
        id:
          type: string
          example: "6585f9e2b1c2d3e4f5a6b7c8"
        gameMode:
          type: string
          enum: [classic, advanced]
          example: "classic"
        players:
          type: array
          items:
            $ref: '#/components/schemas/PlayerRequest'
